/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Feature {
  'description' : string,
  'phase' : { 'later' : null } |
    { 'phase1' : null },
}
export interface Order {
  'id' : bigint,
  'productIds' : Array<bigint>,
  'userId' : Principal,
  'totalAmount' : bigint,
}
export interface PageFeatures { 'features' : Array<Feature>, 'page' : string }
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'price' : bigint,
}
export interface SavedArtifact { 'userId' : Principal, 'productId' : bigint }
export interface User { 'id' : bigint, 'name' : string, 'email' : string }
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<[Array<bigint>, bigint], bigint>,
  'createProduct' : ActorMethod<[string, string, bigint, bigint], bigint>,
  'createUser' : ActorMethod<[string, string], bigint>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeatureSpecification' : ActorMethod<[], Array<PageFeatures>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getMySavedArtifacts' : ActorMethod<[], Array<SavedArtifact>>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getSavedArtifacts' : ActorMethod<[Principal], Array<SavedArtifact>>,
  'getUser' : ActorMethod<[bigint], User>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeSavedArtifact' : ActorMethod<[bigint], undefined>,
  'saveArtifact' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProductStock' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];