/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminAccessLogEntry {
  'id' : bigint,
  'principal' : Principal,
  'timestamp' : bigint,
  'deviceType' : [] | [string],
  'browserInfo' : [] | [string],
}
export interface AdminLoginAttempt {
  'id' : bigint,
  'principal' : Principal,
  'timestamp' : bigint,
  'successful' : boolean,
}
export interface AdminPermissions {
  'canDeactivateStore' : boolean,
  'canApplyDiscounts' : boolean,
  'principal' : Principal,
  'canCreateOrder' : boolean,
  'canManageUsers' : boolean,
  'canCreateProduct' : boolean,
  'canManageInventory' : boolean,
  'canProcessRefunds' : boolean,
  'fullPermissions' : boolean,
  'canRemoveUsers' : boolean,
  'canDeleteProduct' : boolean,
  'isOwner' : boolean,
  'canViewMetrics' : boolean,
  'canEditProduct' : boolean,
}
export type AuditActionType = { 'adminEdit' : null } |
  { 'adminMessage' : null } |
  { 'adminLogin' : null } |
  { 'orderUpdate' : null } |
  { 'couponCreate' : null } |
  { 'couponToggle' : null } |
  { 'adminApproval' : null } |
  { 'adminDecline' : null };
export interface AuditLogEntry {
  'id' : bigint,
  'actionType' : AuditActionType,
  'target' : [] | [Principal],
  'timestamp' : bigint,
  'details' : string,
  'actorPrincipal' : Principal,
}
export interface Event {
  'id' : bigint,
  'principal' : Principal,
  'level' : string,
  'message' : string,
  'timestamp' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Feature {
  'description' : string,
  'phase' : { 'later' : null } |
    { 'phase1' : null },
}
export interface HealthStatus {
  'status' : string,
  'environment' : string,
  'build' : string,
  'deployedVersion' : string,
}
export interface NotificationCounts {
  'newOrders' : bigint,
  'newMessagesCount' : bigint,
  'newTestimonies' : bigint,
  'newQuotes' : bigint,
}
export interface PageFeatures { 'features' : Array<Feature>, 'page' : string }
export interface Testimony {
  'id' : bigint,
  'shortReview' : [] | [string],
  'starRating' : [] | [number],
  'content' : string,
  'video' : [] | [ExternalBlob],
  'author' : string,
  'approved' : boolean,
  'rating' : [] | [bigint],
  'photo' : [] | [ExternalBlob],
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Entry point for admin authentication - allows guest/anonymous access
   */
  'adminLogin' : ActorMethod<[string, boolean, string, string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changeAdminAccessCode' : ActorMethod<[string, string], boolean>,
  'confirmNewCode' : ActorMethod<[string, string], boolean>,
  'getAdminAccessLog' : ActorMethod<[], Array<AdminAccessLogEntry>>,
  'getAdminAttempts' : ActorMethod<[Principal], bigint>,
  'getAdminNotifications' : ActorMethod<[], NotificationCounts>,
  'getAllAdmins' : ActorMethod<[], Array<AdminPermissions>>,
  'getAllAuditLogEntries' : ActorMethod<[], Array<AuditLogEntry>>,
  'getAllTestimonies' : ActorMethod<[], Array<Testimony>>,
  'getAttemptCount' : ActorMethod<[Principal], bigint>,
  'getAuditLogEntriesByType' : ActorMethod<
    [AuditActionType],
    Array<AuditLogEntry>
  >,
  'getAuditLogEntriesForActor' : ActorMethod<[Principal], Array<AuditLogEntry>>,
  'getAuditLogEntry' : ActorMethod<[bigint], [] | [AuditLogEntry]>,
  'getAuditLogStats' : ActorMethod<
    [],
    {
      'total' : bigint,
      'orderUpdateCounts' : bigint,
      'couponCreateCounts' : bigint,
      'approvalCounts' : bigint,
      'messageCounts' : bigint,
      'editCounts' : bigint,
      'declineCounts' : bigint,
      'couponToggleCounts' : bigint,
      'loginCounts' : bigint,
    }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentAdminAccessCode' : ActorMethod<[], [] | [string]>,
  'getEvents' : ActorMethod<[], Array<Event>>,
  'getFeatureSpecification' : ActorMethod<[], Array<PageFeatures>>,
  'getLoginAttempts' : ActorMethod<[], Array<AdminLoginAttempt>>,
  'getOnlyVerifiedTestimonies' : ActorMethod<[], Array<Testimony>>,
  'getPermissions' : ActorMethod<[Principal], [] | [AdminPermissions]>,
  'getRecentAuditLogEntries' : ActorMethod<[bigint], Array<AuditLogEntry>>,
  'getTestimony' : ActorMethod<[bigint], [] | [Testimony]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'healthCheck' : ActorMethod<[], HealthStatus>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAdmins' : ActorMethod<[], Array<AdminPermissions>>,
  'logEvent' : ActorMethod<[string, string], undefined>,
  'resetAdminAttempts' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setOwner' : ActorMethod<[Principal], undefined>,
  /**
   * / If returns "Invalid Access Code" an error message has to be presented in the app
   * / Only on successful returns, the full admin dashboard should become accessible.
   */
  'submitAdminAccessAttempt' : ActorMethod<
    [string, [] | [string], [] | [string]],
    string
  >,
  'updateAdminAccessCode' : ActorMethod<[string], undefined>,
  'verifyAccessCode' : ActorMethod<[string], boolean>,
  /**
   * / Verifies admin access code and grants admin role on success
   * / Allows any caller (including guests) to attempt verification
   */
  'verifyAdminAccess' : ActorMethod<
    [string, [] | [string], [] | [string]],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];