/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminAccessLogEntry {
  'id' : bigint,
  'principal' : Principal,
  'timestamp' : bigint,
}
export interface AdminLoginAttempt {
  'id' : bigint,
  'principal' : Principal,
  'timestamp' : bigint,
  'successful' : boolean,
}
export interface Event {
  'id' : bigint,
  'principal' : Principal,
  'level' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface Feature {
  'description' : string,
  'phase' : { 'later' : null } |
    { 'phase1' : null },
}
export interface HealthStatus {
  'status' : string,
  'environment' : string,
  'build' : string,
  'deployedVersion' : string,
}
export interface PageFeatures { 'features' : Array<Feature>, 'page' : string }
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignAdminRole' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAdminAccessLog' : ActorMethod<[], Array<AdminAccessLogEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEvents' : ActorMethod<[], Array<Event>>,
  'getFeatureSpecification' : ActorMethod<[], Array<PageFeatures>>,
  'getLoginAttempts' : ActorMethod<[], Array<AdminLoginAttempt>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'healthCheck' : ActorMethod<[], HealthStatus>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logEvent' : ActorMethod<[string, string], undefined>,
  'removeAdminRole' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'verifyAdminAccess' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];