/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'productIds' : IDL.Vec(IDL.Nat),
  'userId' : IDL.Principal,
  'totalAmount' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'price' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const Feature = IDL.Record({
  'description' : IDL.Text,
  'phase' : IDL.Variant({ 'later' : IDL.Null, 'phase1' : IDL.Null }),
});
export const PageFeatures = IDL.Record({
  'features' : IDL.Vec(Feature),
  'page' : IDL.Text,
});
export const SavedArtifact = IDL.Record({
  'userId' : IDL.Principal,
  'productId' : IDL.Nat,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrder' : IDL.Func([IDL.Vec(IDL.Nat), IDL.Nat], [IDL.Nat], []),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeatureSpecification' : IDL.Func([], [IDL.Vec(PageFeatures)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMySavedArtifacts' : IDL.Func([], [IDL.Vec(SavedArtifact)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getSavedArtifacts' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(SavedArtifact)],
      ['query'],
    ),
  'getUser' : IDL.Func([IDL.Nat], [User], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeSavedArtifact' : IDL.Func([IDL.Nat], [], []),
  'saveArtifact' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProductStock' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'productIds' : IDL.Vec(IDL.Nat),
    'userId' : IDL.Principal,
    'totalAmount' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const Feature = IDL.Record({
    'description' : IDL.Text,
    'phase' : IDL.Variant({ 'later' : IDL.Null, 'phase1' : IDL.Null }),
  });
  const PageFeatures = IDL.Record({
    'features' : IDL.Vec(Feature),
    'page' : IDL.Text,
  });
  const SavedArtifact = IDL.Record({
    'userId' : IDL.Principal,
    'productId' : IDL.Nat,
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrder' : IDL.Func([IDL.Vec(IDL.Nat), IDL.Nat], [IDL.Nat], []),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeatureSpecification' : IDL.Func(
        [],
        [IDL.Vec(PageFeatures)],
        ['query'],
      ),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMySavedArtifacts' : IDL.Func([], [IDL.Vec(SavedArtifact)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getSavedArtifacts' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(SavedArtifact)],
        ['query'],
      ),
    'getUser' : IDL.Func([IDL.Nat], [User], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeSavedArtifact' : IDL.Func([IDL.Nat], [], []),
    'saveArtifact' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProductStock' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };